kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: edge-server-cv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-server-cv
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Pods
    pods:
      metricName: flask_http_requests_per_second
      targetAverageValue: 300m
