apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: python-custom-autoscaler-big
spec:
  template:
    spec:
      containers:
      - name: python-custom-autoscaler-big
        image: rfc_scaler_v1:latest ##cvcpa:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-server-cv 
  roleRequiresMetricsServer: false
  config: 
    - name: interval
      value: "15000"