apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-server-cv
  labels:
    app: edge-server-cv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-server-cv
  template:
    metadata:
      labels:
        app: edge-server-cv
    spec:
      containers:
      - image: imagerec:latest
        name: edge-server-cv
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        env:
        - name: EDGE_SERVER_PORT
          value: '8000'
        ports:
        - name: es-port
          containerPort: 8000
        imagePullPolicy: Never
