apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: python-custom-autoscaler-small
spec:
  template:
    spec:
      containers:
      - name: python-custom-autoscaler-small
        image: cxcpa:latest ##pickle_cpa8:latest
        imagePullPolicy: IfNotPresent
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-server-cx
  roleRequiresMetricsServer: false
  config: 
    - name: interval
      value: "10000"