apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-server-cv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-server-cv
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Pods
    pods:
      metric:
        name: edge_server_art_for_30
      target:
        type: AverageValue
        averageValue: 320m