apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-server-cv
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-server-cv
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      metric:
        name: edge_server_cpu_per_limit_for_60
      describedObject : 
        apiVersion: /v1
        kind: Service
        name: edge-server-cv
      target:
        type: Value
        value: 60000m