{
 "title": "Edge server dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "avg(\n    sum by (pod) (\n      rate(flask_http_request_total{service=\"edge-server-cv\"} [2s])\n  )\n)",
     "legendFormat": "Average Request Rate"
    },
    {
     "expr": "sum by (pod) (\n  sum by (pod, status) (\n    rate(flask_http_request_total{service=\"edge-server-cv\"} [2s])\n  )\n)",
     "legendFormat": "{{pod}} Requests"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=\"edge-server-cv\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=\"edge-server-cv\"} [10s])\n    )\n)",
     "legendFormat": "Average Response Rate"
    },
    {
     "expr": "avg by (pod) (\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_sum{service=\"edge-server-cv\"} [10s])\n    ) /\n    sum by (pod) (\n      rate(flask_http_request_duration_seconds_count{service=\"edge-server-cv\"} [10s])\n    )\n)",
     "legendFormat": "{{pod}} Response"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{ container=~\"edge-server.*\"} [1m])\n)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (pod) (\n  rate(container_cpu_usage_seconds_total{ container=~\"edge-server.*\"} [1m])\n  )",
     "legendFormat": "{{pod}} cpu"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"edge-server-cv-.*\"})",
     "legendFormat": "Total Memory Usage"
    },
    {
     "expr": "sum  by (pod) (container_memory_working_set_bytes{pod=~\"edge-server-cv-.*\"})",
     "legendFormat": "{{pod}} Usage"
    }
   ]
  },
  {
   "title": "Number of pods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(count by (pod) (container_memory_usage_bytes{ container=~\"edge-server.*\"}))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}