evaluate:
  type: "shell"
  timeout: 2500
  shell:
    entrypoint: "python"
    command:
      - "/evaluate.py"
metric:
  type: "shell"
  timeout: 2500
  shell:
    entrypoint: "python"
    command:
      - "/metric.py"
kubernetesMetricSpecs:      
- type: Object
  object:
    metric:
      name: edge_server_request_rate_for_30
    describedObject:
      apiVersion: /v1
      kind: Service
      name: edge-server-cv
    target:
      type: Value
minReplicas: 1
maxReplicas: 5      
runMode: "per-resource"

